### PR TITLE
Translations, Updates, Images

### PR DESCRIPTION
**Pull request by TrishaMinela**
Updated as of March 2024

### CODE REVIEW

**Comment by flybaflyba** [comment]
> Updated as of March 2024



> Updated as of March 2024

Hi TrishaMinela, I see you created a pull request to this repo. Are you a student of Brother Draper? Btw I'm the first author of this temple app. If you are introduced here by Brother Draper and/or want to work on this app, please let me know you email, I can add you to the project.

**Comment by TrishaMinela** [comment]
Yes I work as his Research Assistant atm. We’re trying to figure out where
to pull and push requests 😅 I think I was confused because I was sent a
link on which repository to fork.

**Comment by flybaflyba** [comment]
cool, I think pull request will need approval from an ower of this repo, that's why I'm receving an notification for the pull request. 
Anyway, I will add you in this project so that you can create/merge branchs in the original repo. If there are other students wants to join, send me an email at litian_zhang17@163.com, I can add them from there. Help me to tell Brother Draper that Litian said Hi😄.

**Comment by TrishaMinela** [comment]
Thank you! He said he’s glad that you still look at this project.

**Comment by TrishaMinela** [comment]
Hi again. Sorry I think I didn't accept your invitation to be part of this project and it expired. Also is this the repository that Brother Draper uses to update the actual android temples app? He is wondering how if this repository is updated by me, does it update the one on his end? He doesn't see my commits. Thanks

**Comment by flybaflyba** [comment]
Just added you. 
I don't think Brother Draper worked on this repo. If you update this repo, then only this repo gets updated. I don't think any other repo will synchronize in any way unless a mannual fork is made to this repo to create a new one somewhere else. 

You can also check with https://github.com/Low-go about how the updates has been done before. He made the last update to this repo in Nov. 2023.

I just invited Brother Draper to this repo too, I missed his email earlier.

**Pull request merged**
